name: Check for status change
on:
  pull_request:
    types:
      - closed

jobs:
  StatusChangeCheck:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check status
        id: status
        continue-on-error: true
        run:  echo ::set-output name=hipstatus::$(git diff HEAD^ HEAD -G'status:' | egrep "^\+status:" >> status && cut -d ":" -f2 status && rm -f status)
      
      - name: Get HIP name
        if: steps.status.outcome == 'success'
        id: hip_name
        run:  echo ::set-output name=hipname::$(basename -- $(git diff --name-only HEAD HEAD~1 | grep .md) .md)

      - name: Discord notification
        if: "${{ steps.hip_name.outputs.hipname != '.md' }}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD }}
        uses: Ilshidur/action-discord@master
        with:
          args: '${{ steps.hip_name.outputs.hipname }} moved into ${{ steps.status.outputs.hipstatus }} status https://hips.hedera.com/hip/${{ steps.hip_name.outputs.hipname }}'