# This is a github actions workflow that retrieves the modified hips and runs a validator script against them written in Node.
name: Validate HIP
on: [pull_request]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  ValidateHIP:
    runs-on: [self-hosted, Linux, medium, ephemeral]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Check out repository code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "12.x"

      - name: Install jq
        run: sudo apt-get install jq

      - name: Validate HIPs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          PR_DATA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/files")
          MD_FILES=$(echo "$PR_DATA" | jq -r '.[] | select(.filename | test(".md$")) | .filename')

          for FILE in $MD_FILES; do
            FULL_PATH="${{ github.workspace }}/$FILE"
            if [[ -f "$FULL_PATH" ]]; then
              node "${{ github.workspace }}/scripts/validateHIP.js" "$FULL_PATH"
            else
              echo "No file found for $FILE"
              exit 1
            fi
          done
